### ISSUE TITLE
http://kora.kpu.ca/ is hard-coded in the Solr lookup

### ISSUE THREAD

**Issue by mjordan** [bondjimbond/old_url_lookup#6]
https://github.com/bondjimbond/islandora_url_redirector/blob/master/islandora_url_redirector.module#L96 hard-codes `http://kora.kpu.ca/` in the solr lookup. I think the value of `$base_url` should be used instead. That should work if the site running this module has the hostname that is used in the Solr data (which should always be the case).

**Comment by bondjimbond** [comment]
Thanks for finding that, @mjordan. Turns out the line wasn't necessary at all. This $path is for identifying the string to look up in the identifier field. Setting it with $base_url breaks things (unless the base URL is the same). Removing it entirely works fine.
